name: 'cost_governance_dbt'
version: '1.0.0'

profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  credit_price_usd: 4.00

# No +database and +schema as dbt will use it from profiles.yml
models:
  cost_governance_dbt:
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
    marts:
      cost:
        +materialized: table
      performance:
        +materialized: table