cost_governance_profile:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: sq73917
      user: JULIANROCCI
      role: ACCOUNTADMIN
      database: MGMT_DB_DEV
      warehouse: MGMT_WH_DEV
      schema: COST_GOVERNANCE
      threads: 4