# dbt_project.yml
name: 'cost_governance'
version: '1.0.0'
config-version: 2

# Connection to the profile defined above
profile: 'cost_governance_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Global configurations for models
models:
  cost_governance:
    # No +database as dbt will use it from profiles.yml file
    # Layer 1: Raw data cleaning
    staging:
      +schema: staging
      +materialized: view
    
    # Layer 2: Business logic & KPIs calculation
    intermediate:
      +schema: intermediate
      +materialized: ephemeral
    
    # Layer 3: Final reporting gold tables
    marts:
      +materialized: table
      cost:
        +schema: mart_cost
      performance:
        +schema: mart_performance
      governance:
        +schema: mart_governance