cost_governance_profile:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: sq73917
      user: JULIANROCCI
      role: ACCOUNTADMIN
      database: GOVERNANCE_DB
      warehouse: COMPUTE_WH
      schema: main
      threads: 4