-- Define only config tables ( other will be created automatically by dbt )
DEFINE TABLE {{mgmt_db}}.CONFIG.COST_CENTER_MAPPING (
    COST_CENTER_CODE VARCHAR(50) NOT NULL,
    COST_CENTER_NAME VARCHAR(256) NOT NULL,
    DOMAIN VARCHAR(50) NOT NULL,
    DEPARTMENT VARCHAR(256),
    BUDGET_MONTHLY_CREDITS NUMBER(12,2),
    OWNER_EMAIL VARCHAR(256),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Reference — maps cost center codes to departments and monthly budgets';

DEFINE TABLE {{mgmt_db}}.CONFIG.WAREHOUSE_COST_CONFIG (
    WAREHOUSE_NAME VARCHAR(256) NOT NULL,
    DOMAIN VARCHAR(50) NOT NULL,
    COST_CENTER_CODE VARCHAR(50),
    CREDIT_PRICE_USD NUMBER(10,4) DEFAULT {{credit_price_usd}},
    ALERT_THRESHOLD_PCT NUMBER(5,2) DEFAULT 80.00,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Reference — maps warehouses to domains, cost centers and alert thresholds';

DEFINE TABLE {{mgmt_db}}.CONFIG.QUERY_TAG_RULES (
    TAG_PATTERN VARCHAR(1024) NOT NULL,
    DOMAIN VARCHAR(50),
    COST_CENTER_CODE VARCHAR(50),
    PIPELINE_NAME VARCHAR(256),
    DESCRIPTION VARCHAR(1024),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Reference — rules for parsing query_tag JSON into domain/cost_center attribution';