/* Resource Monitors to prevent budget overruns per domain. */

USE ROLE ACCOUNTADMIN;

-- GLOBAL ACCOUNT MONITOR

CREATE OR REPLACE RESOURCE MONITOR GLOBAL_BUDGET
    CREDIT_QUOTA = 2000
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS 
        ON 80 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;


-- DOMAIN SPECIFIC MONITORS

CREATE OR REPLACE RESOURCE MONITOR TRANSFORM_MONITOR
    CREDIT_QUOTA = 500
    FREQUENCY = MONTHLY
    TRIGGERS 
        ON 90 PERCENT DO NOTIFY
        -- SUSPEND_IMMEDIATE to avoid a dbt script to keep going
        ON 100 PERCENT DO SUSPEND_IMMEDIATE;

CREATE OR REPLACE RESOURCE MONITOR FINANCE_MONITOR
    CREDIT_QUOTA = 200
    FREQUENCY = MONTHLY
    TRIGGERS 
        ON 80 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

CREATE OR REPLACE RESOURCE MONITOR MARKETING_MONITOR
    CREDIT_QUOTA = 300
    FREQUENCY = MONTHLY
    TRIGGERS 
        ON 80 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

CREATE OR REPLACE RESOURCE MONITOR ECOMMERCE_MONITOR
    CREDIT_QUOTA = 400
    FREQUENCY = MONTHLY
    TRIGGERS 
        ON 80 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

CREATE OR REPLACE RESOURCE MONITOR RETAIL_MONITOR
    CREDIT_QUOTA = 300
    FREQUENCY = MONTHLY
    TRIGGERS 
        ON 80 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

CREATE OR REPLACE RESOURCE MONITOR ANALYTICS_MONITOR
    CREDIT_QUOTA = 300
    FREQUENCY = MONTHLY
    TRIGGERS 
        ON 80 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;


-- MONITOR ASSIGNMENTS

ALTER ACCOUNT SET RESOURCE_MONITOR = GLOBAL_BUDGET;

ALTER WAREHOUSE TRANSFORM_WH SET RESOURCE_MONITOR = TRANSFORM_MONITOR;

ALTER WAREHOUSE FIN_WH SET RESOURCE_MONITOR = FINANCE_MONITOR;

ALTER WAREHOUSE MKT_WH SET RESOURCE_MONITOR = MARKETING_MONITOR;

ALTER WAREHOUSE ECO_WH SET RESOURCE_MONITOR = ECOMMERCE_MONITOR;

ALTER WAREHOUSE RET_WH SET RESOURCE_MONITOR = RETAIL_MONITOR;

ALTER WAREHOUSE ANA_WH SET RESOURCE_MONITOR = ANALYTICS_MONITOR;