/* RBAC & Permissions Setup */

USE ROLE DCM_ADMIN;

-- ROLES CREATION

CREATE ROLE IF NOT EXISTS DBT_ROLE
    COMMENT = 'Service Role for dbt Transformations';

CREATE ROLE IF NOT EXISTS ANA_ROLE
    COMMENT = 'Functional Role for Data Analysts';

CREATE ROLE IF NOT EXISTS FIN_ROLE
    COMMENT = 'Functional Role for Finance Department';

CREATE ROLE IF NOT EXISTS MKT_ROLE
    COMMENT = 'Functional Role for Marketing Department';

CREATE ROLE IF NOT EXISTS ECO_ROLE
    COMMENT = 'Functional Role for E-commerce Department';

CREATE ROLE IF NOT EXISTS RET_ROLE
    COMMENT = 'Functional Role for Retail Department';


-- ROLE HIERARCHY

GRANT ROLE DBT_ROLE TO ROLE SYSADMIN;

GRANT ROLE ANA_ROLE TO ROLE SYSADMIN;

GRANT ROLE FIN_ROLE TO ROLE SYSADMIN;

GRANT ROLE MKT_ROLE TO ROLE SYSADMIN;

GRANT ROLE ECO_ROLE TO ROLE SYSADMIN;

GRANT ROLE RET_ROLE TO ROLE SYSADMIN;


-- WAREHOUSE USAGE

GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE DBT_ROLE;

GRANT USAGE ON WAREHOUSE ANA_WH TO ROLE ANA_ROLE;

GRANT USAGE ON WAREHOUSE FIN_WH TO ROLE FIN_ROLE;

GRANT USAGE ON WAREHOUSE MKT_WH TO ROLE MKT_ROLE;

GRANT USAGE ON WAREHOUSE ECO_WH TO ROLE ECO_ROLE;

GRANT USAGE ON WAREHOUSE RET_WH TO ROLE RET_ROLE;


-- DATABASE USAGE (GOVERNANCE HUB)

GRANT ALL PRIVILEGES ON DATABASE {{ gov_db }} TO ROLE DBT_ROLE;

GRANT USAGE ON DATABASE {{ gov_db }} TO ROLE ANA_ROLE;

GRANT USAGE ON DATABASE {{ gov_db }} TO ROLE FIN_ROLE;

GRANT USAGE ON DATABASE {{ gov_db }} TO ROLE MKT_ROLE;

GRANT USAGE ON DATABASE {{ gov_db }} TO ROLE ECO_ROLE;

GRANT USAGE ON DATABASE {{ gov_db }} TO ROLE RET_ROLE;


-- MART ACCESS

-- Analytics: Full Marts visibility
GRANT USAGE ON SCHEMA {{ gov_db }}.MART_COST TO ROLE ANA_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA {{ gov_db }}.MART_COST TO ROLE ANA_ROLE;

GRANT USAGE ON SCHEMA {{ gov_db }}.MART_PERFORMANCE TO ROLE ANA_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA {{ gov_db }}.MART_PERFORMANCE TO ROLE ANA_ROLE;


-- Finance: Cost and Credits visibility
GRANT USAGE ON SCHEMA {{ gov_db }}.MART_COST TO ROLE FIN_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA {{ gov_db }}.MART_COST TO ROLE FIN_ROLE;

-- E-commerce & Retail: Performance and Efficiency visibility
GRANT USAGE ON SCHEMA {{ gov_db }}.MART_PERFORMANCE TO ROLE ECO_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA {{ gov_db }}.MART_PERFORMANCE TO ROLE ECO_ROLE;

GRANT USAGE ON SCHEMA {{ gov_db }}.MART_PERFORMANCE TO ROLE RET_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA {{ gov_db }}.MART_PERFORMANCE TO ROLE RET_ROLE;