/* Virtual Warehouse orchestration with domain isolation. */

USE ROLE DCM_ADMIN;

-- INFRASTRUCTURE & PIPELINES

CREATE WAREHOUSE IF NOT EXISTS TRANSFORM_WH
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Main engine for DCM deployment and dbt transformations';


-- DOMAIN SPECIFIC ENGINES

CREATE WAREHOUSE IF NOT EXISTS FIN_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Dedicated warehouse for Finance domain workloads';

CREATE WAREHOUSE IF NOT EXISTS MKT_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Dedicated warehouse for Marketing domain workloads';

CREATE WAREHOUSE IF NOT EXISTS ECO_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Dedicated warehouse for E-commerce domain workloads';

CREATE WAREHOUSE IF NOT EXISTS RET_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Dedicated warehouse for Retail domain workloads';

CREATE WAREHOUSE IF NOT EXISTS ANA_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Dedicated warehouse for Analytics domain workloads';