-- =============================================================================
-- DCM Cost Governance — Post-deploy Future Grants
-- Run as DCM_DEPLOYER, after each DCM deploy.
-- Ensures tables/views created by dbt auto-inherit grants.
-- =============================================================================

CREATE OR REPLACE PROCEDURE SETUP_FUTURE_GRANTS(ENV VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
DECLARE
    env_suffix VARCHAR;
    mgmt_db VARCHAR;
    domains ARRAY;
    i INTEGER;
    db VARCHAR;
BEGIN
    CASE UPPER(ENV)
        WHEN 'DEV'  THEN env_suffix := '_DEV';  mgmt_db := 'MGMT_DB_DEV';
        WHEN 'UAT'  THEN env_suffix := '_UAT';  mgmt_db := 'MGMT_DB_UAT';
        WHEN 'PROD' THEN env_suffix := '';        mgmt_db := 'MGMT_DB';
        ELSE RETURN 'ERROR: Invalid environment. Use DEV, UAT, or PROD.';
    END CASE;

    domains := ARRAY_CONSTRUCT('FINANCE', 'MARKETING', 'ECOMMERCE', 'RETAIL', 'LOYALTY', 'SALES', 'HR');

    FOR i IN 0 TO ARRAY_SIZE(domains) - 1 DO
        db := GET(domains, i) || '_DB' || env_suffix;

        -- READER → future SELECT on MARTS (tables + views)
        EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE TABLES IN SCHEMA ' || db || '.MARTS TO DATABASE ROLE ' || db || '.READER';
        EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE VIEWS IN SCHEMA ' || db || '.MARTS TO DATABASE ROLE ' || db || '.READER';

        -- ANALYST → future SELECT on STAGING (tables + views)
        EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE TABLES IN SCHEMA ' || db || '.STAGING TO DATABASE ROLE ' || db || '.ANALYST';
        EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE VIEWS IN SCHEMA ' || db || '.STAGING TO DATABASE ROLE ' || db || '.ANALYST';

        -- ADMIN → future DML on RAW + DDL schemas
        EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ' || db || '.RAW TO DATABASE ROLE ' || db || '.ADMIN';
        EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE VIEWS IN SCHEMA ' || db || '.RAW TO DATABASE ROLE ' || db || '.ADMIN';

        -- INGESTION_ROLE → future DML on RAW
        EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ' || db || '.RAW TO ROLE INGESTION_ROLE' || env_suffix;

        -- TRANSFORM_ROLE → future SELECT on RAW, future DML on STAGING + MARTS
        EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE TABLES IN SCHEMA ' || db || '.RAW TO ROLE TRANSFORM_ROLE' || env_suffix;
        EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE VIEWS IN SCHEMA ' || db || '.RAW TO ROLE TRANSFORM_ROLE' || env_suffix;

        EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ' || db || '.STAGING TO ROLE TRANSFORM_ROLE' || env_suffix;
        EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE VIEWS IN SCHEMA ' || db || '.STAGING TO ROLE TRANSFORM_ROLE' || env_suffix;

        EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ' || db || '.MARTS TO ROLE TRANSFORM_ROLE' || env_suffix;
        EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE VIEWS IN SCHEMA ' || db || '.MARTS TO ROLE TRANSFORM_ROLE' || env_suffix;
    END FOR;

    -- ANALYTICS DB
    LET ana_db VARCHAR := 'ANALYTICS_DB' || env_suffix;
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE TABLES IN SCHEMA ' || ana_db || '.MARTS TO DATABASE ROLE ' || ana_db || '.READER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE VIEWS IN SCHEMA ' || ana_db || '.MARTS TO DATABASE ROLE ' || ana_db || '.READER';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ' || ana_db || '.MARTS TO ROLE TRANSFORM_ROLE' || env_suffix;
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE VIEWS IN SCHEMA ' || ana_db || '.MARTS TO ROLE TRANSFORM_ROLE' || env_suffix;

    -- MGMT DB: GOVERNANCE_READER → future SELECT on governance schemas
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE TABLES IN SCHEMA ' || mgmt_db || '.COST_GOVERNANCE TO DATABASE ROLE ' || mgmt_db || '.GOVERNANCE_READER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE VIEWS IN SCHEMA ' || mgmt_db || '.COST_GOVERNANCE TO DATABASE ROLE ' || mgmt_db || '.GOVERNANCE_READER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE TABLES IN SCHEMA ' || mgmt_db || '.ACCESS_GOVERNANCE TO DATABASE ROLE ' || mgmt_db || '.GOVERNANCE_READER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE VIEWS IN SCHEMA ' || mgmt_db || '.ACCESS_GOVERNANCE TO DATABASE ROLE ' || mgmt_db || '.GOVERNANCE_READER';

    -- MGMT DB: GOVERNANCE_ADMIN → future DML on all mgmt schemas
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ' || mgmt_db || '.CONFIG TO DATABASE ROLE ' || mgmt_db || '.GOVERNANCE_ADMIN';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ' || mgmt_db || '.ORCHESTRATION TO DATABASE ROLE ' || mgmt_db || '.GOVERNANCE_ADMIN';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ' || mgmt_db || '.COST_GOVERNANCE TO DATABASE ROLE ' || mgmt_db || '.GOVERNANCE_ADMIN';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ' || mgmt_db || '.ACCESS_GOVERNANCE TO DATABASE ROLE ' || mgmt_db || '.GOVERNANCE_ADMIN';

    -- TRANSFORM_ROLE → future DML on MGMT governance schemas
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ' || mgmt_db || '.COST_GOVERNANCE TO ROLE TRANSFORM_ROLE' || env_suffix;
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE VIEWS IN SCHEMA ' || mgmt_db || '.COST_GOVERNANCE TO ROLE TRANSFORM_ROLE' || env_suffix;
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ' || mgmt_db || '.ACCESS_GOVERNANCE TO ROLE TRANSFORM_ROLE' || env_suffix;
    EXECUTE IMMEDIATE 'GRANT SELECT ON FUTURE VIEWS IN SCHEMA ' || mgmt_db || '.ACCESS_GOVERNANCE TO ROLE TRANSFORM_ROLE' || env_suffix;

    RETURN 'SUCCESS: Future grants applied for ' || UPPER(ENV) || ' environment.';
END;

-- GRANTS to the prodecure for CI/CD ( to be executed only once then per env then drop the line)
-- GRANT USAGE ON PROCEDURE {{mgmt_db}}.DCM.SETUP_FUTURE_GRANTS(VARCHAR) TO ROLE DCM_DEPLOYER;