-- ============================================================
-- ONE-SHOT FUTURE GRANTS SETUP
-- Run once on DEV only. For new test tables created.
-- Ensures new tables/views auto-inherit grants.
-- No need on other env as DCM will handle the grants
-- ============================================================

-- DOMAIN DBs: READER → future SELECT on MARTS
GRANT SELECT ON FUTURE TABLES IN SCHEMA FINANCE_DB_DEV.MARTS TO DATABASE ROLE FINANCE_DB_DEV.READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MARKETING_DB_DEV.MARTS TO DATABASE ROLE MARKETING_DB_DEV.READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ECOMMERCE_DB_DEV.MARTS TO DATABASE ROLE ECOMMERCE_DB_DEV.READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_DB_DEV.MARTS TO DATABASE ROLE RETAIL_DB_DEV.READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA LOYALTY_DB_DEV.MARTS TO DATABASE ROLE LOYALTY_DB_DEV.READER;

-- DOMAIN DBs: ANALYST → future SELECT on STAGING
GRANT SELECT ON FUTURE TABLES IN SCHEMA FINANCE_DB_DEV.STAGING TO DATABASE ROLE FINANCE_DB_DEV.ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MARKETING_DB_DEV.STAGING TO DATABASE ROLE MARKETING_DB_DEV.ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ECOMMERCE_DB_DEV.STAGING TO DATABASE ROLE ECOMMERCE_DB_DEV.ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_DB_DEV.STAGING TO DATABASE ROLE RETAIL_DB_DEV.ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA LOYALTY_DB_DEV.STAGING TO DATABASE ROLE LOYALTY_DB_DEV.ANALYST;

-- DOMAIN DBs: ADMIN → future DML on RAW
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA FINANCE_DB_DEV.RAW TO DATABASE ROLE FINANCE_DB_DEV.ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA MARKETING_DB_DEV.RAW TO DATABASE ROLE MARKETING_DB_DEV.ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ECOMMERCE_DB_DEV.RAW TO DATABASE ROLE ECOMMERCE_DB_DEV.ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA RETAIL_DB_DEV.RAW TO DATABASE ROLE RETAIL_DB_DEV.ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA LOYALTY_DB_DEV.RAW TO DATABASE ROLE LOYALTY_DB_DEV.ADMIN;

-- ANALYTICS DB: READER → future SELECT on MARTS
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DB_DEV.MARTS TO DATABASE ROLE ANALYTICS_DB_DEV.READER;

-- MGMT DB: GOVERNANCE_READER → future SELECT on governance schemas
GRANT SELECT ON FUTURE TABLES IN SCHEMA MGMT_DB_DEV.COST_GOVERNANCE TO DATABASE ROLE MGMT_DB_DEV.GOVERNANCE_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MGMT_DB_DEV.ACCESS_GOVERNANCE TO DATABASE ROLE MGMT_DB_DEV.GOVERNANCE_READER;

-- MGMT DB: GOVERNANCE_ADMIN → future DML on all mgmt schemas
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA MGMT_DB_DEV.CONFIG TO DATABASE ROLE MGMT_DB_DEV.GOVERNANCE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA MGMT_DB_DEV.ORCHESTRATION TO DATABASE ROLE MGMT_DB_DEV.GOVERNANCE_ADMIN;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA MGMT_DB_DEV.COST_GOVERNANCE TO DATABASE ROLE MGMT_DB_DEV.GOVERNANCE_ADMIN;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA MGMT_DB_DEV.ACCESS_GOVERNANCE TO DATABASE ROLE MGMT_DB_DEV.GOVERNANCE_ADMIN;

-- INGESTION_ROLE → future DML on all RAW schemas
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA FINANCE_DB_DEV.RAW TO ROLE INGESTION_ROLE_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA MARKETING_DB_DEV.RAW TO ROLE INGESTION_ROLE_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ECOMMERCE_DB_DEV.RAW TO ROLE INGESTION_ROLE_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA RETAIL_DB_DEV.RAW TO ROLE INGESTION_ROLE_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA LOYALTY_DB_DEV.RAW TO ROLE INGESTION_ROLE_DEV;

-- TRANSFORM_ROLE → future SELECT on RAW, future DML on STAGING + MARTS
GRANT SELECT ON FUTURE TABLES IN SCHEMA FINANCE_DB_DEV.RAW TO ROLE TRANSFORM_ROLE_DEV;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MARKETING_DB_DEV.RAW TO ROLE TRANSFORM_ROLE_DEV;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ECOMMERCE_DB_DEV.RAW TO ROLE TRANSFORM_ROLE_DEV;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_DB_DEV.RAW TO ROLE TRANSFORM_ROLE_DEV;
GRANT SELECT ON FUTURE TABLES IN SCHEMA LOYALTY_DB_DEV.RAW TO ROLE TRANSFORM_ROLE_DEV;

GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA FINANCE_DB_DEV.STAGING TO ROLE TRANSFORM_ROLE_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA MARKETING_DB_DEV.STAGING TO ROLE TRANSFORM_ROLE_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ECOMMERCE_DB_DEV.STAGING TO ROLE TRANSFORM_ROLE_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA RETAIL_DB_DEV.STAGING TO ROLE TRANSFORM_ROLE_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA LOYALTY_DB_DEV.STAGING TO ROLE TRANSFORM_ROLE_DEV;

GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA FINANCE_DB_DEV.MARTS TO ROLE TRANSFORM_ROLE_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA MARKETING_DB_DEV.MARTS TO ROLE TRANSFORM_ROLE_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ECOMMERCE_DB_DEV.MARTS TO ROLE TRANSFORM_ROLE_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA RETAIL_DB_DEV.MARTS TO ROLE TRANSFORM_ROLE_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA LOYALTY_DB_DEV.MARTS TO ROLE TRANSFORM_ROLE_DEV;

GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ANALYTICS_DB_DEV.MARTS TO ROLE TRANSFORM_ROLE_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA MGMT_DB_DEV.COST_GOVERNANCE TO ROLE TRANSFORM_ROLE_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA MGMT_DB_DEV.ACCESS_GOVERNANCE TO ROLE TRANSFORM_ROLE_DEV;