{% macro _domain_roles(db) %}
DEFINE DATABASE ROLE {{db}}.READER
    COMMENT = 'Read-only access to MARTS';

DEFINE DATABASE ROLE {{db}}.ANALYST
    COMMENT = 'Read access to STAGING + MARTS';

DEFINE DATABASE ROLE {{db}}.ADMIN
    COMMENT = 'Full access — DDL + DML on all schemas';

GRANT DATABASE ROLE {{db}}.READER TO DATABASE ROLE {{db}}.ANALYST;
GRANT DATABASE ROLE {{db}}.ANALYST TO DATABASE ROLE {{db}}.ADMIN;
GRANT DATABASE ROLE {{db}}.ADMIN TO ROLE SYSADMIN;

GRANT USAGE ON DATABASE {{db}} TO DATABASE ROLE {{db}}.READER;
GRANT USAGE ON SCHEMA {{db}}.MARTS TO DATABASE ROLE {{db}}.READER;
GRANT SELECT ON ALL TABLES IN SCHEMA {{db}}.MARTS TO DATABASE ROLE {{db}}.READER;

GRANT USAGE ON SCHEMA {{db}}.STAGING TO DATABASE ROLE {{db}}.ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA {{db}}.STAGING TO DATABASE ROLE {{db}}.ANALYST;

GRANT USAGE ON SCHEMA {{db}}.RAW TO DATABASE ROLE {{db}}.ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {{db}}.RAW TO DATABASE ROLE {{db}}.ADMIN;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA {{db}}.RAW TO DATABASE ROLE {{db}}.ADMIN;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA {{db}}.STAGING TO DATABASE ROLE {{db}}.ADMIN;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA {{db}}.MARTS TO DATABASE ROLE {{db}}.ADMIN;

{% endmacro %}

{% macro _analytics_roles(db) %}
DEFINE DATABASE ROLE {{db}}.READER
    COMMENT = 'Read-only access to cross-domain MARTS';

DEFINE DATABASE ROLE {{db}}.ADMIN
    COMMENT = 'Full access — DDL + DML on MARTS';

GRANT DATABASE ROLE {{db}}.READER TO DATABASE ROLE {{db}}.ADMIN;
GRANT DATABASE ROLE {{db}}.ADMIN TO ROLE SYSADMIN;

GRANT USAGE ON DATABASE {{db}} TO DATABASE ROLE {{db}}.READER;
GRANT USAGE ON SCHEMA {{db}}.MARTS TO DATABASE ROLE {{db}}.READER;
GRANT SELECT ON ALL TABLES IN SCHEMA {{db}}.MARTS TO DATABASE ROLE {{db}}.READER;

GRANT CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE ON SCHEMA {{db}}.MARTS TO DATABASE ROLE {{db}}.ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {{db}}.MARTS TO DATABASE ROLE {{db}}.ADMIN;
{% endmacro %}


-- WAREHOUSE ACCESS (account roles — WH grants need account roles)

{% for wh in warehouses %}
DEFINE ROLE {{wh.name}}_WH{{env_suffix}}_USER
    COMMENT = 'Warehouse usage — {{wh.comment}}';

GRANT USAGE ON WAREHOUSE {{wh.name}}_WH{{env_suffix}} TO ROLE {{wh.name}}_WH{{env_suffix}}_USER;
GRANT ROLE {{wh.name}}_WH{{env_suffix}}_USER TO ROLE SYSADMIN;
{% endfor %}


-- DOMAIN DATABASE ROLES (3-tier: READER → ANALYST → ADMIN)

{{ _domain_roles(fin_db) }}
{{ _domain_roles(mkt_db) }}
{{ _domain_roles(eco_db) }}
{{ _domain_roles(ret_db) }}
{{ _domain_roles(loy_db) }}

{{ _analytics_roles(ana_db) }}


-- MANAGEMENT DB ROLES

DEFINE DATABASE ROLE {{mgmt_db}}.GOVERNANCE_READER
    COMMENT = 'Read-only access to governance schemas';

DEFINE DATABASE ROLE {{mgmt_db}}.GOVERNANCE_ADMIN
    COMMENT = 'Full access to governance and config schemas';

GRANT DATABASE ROLE {{mgmt_db}}.GOVERNANCE_READER TO DATABASE ROLE {{mgmt_db}}.GOVERNANCE_ADMIN;
GRANT DATABASE ROLE {{mgmt_db}}.GOVERNANCE_ADMIN TO ROLE SYSADMIN;

GRANT USAGE ON DATABASE {{mgmt_db}} TO DATABASE ROLE {{mgmt_db}}.GOVERNANCE_READER;
GRANT USAGE ON SCHEMA {{mgmt_db}}.COST_GOVERNANCE TO DATABASE ROLE {{mgmt_db}}.GOVERNANCE_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA {{mgmt_db}}.COST_GOVERNANCE TO DATABASE ROLE {{mgmt_db}}.GOVERNANCE_READER;

GRANT USAGE ON SCHEMA {{mgmt_db}}.ACCESS_GOVERNANCE TO DATABASE ROLE {{mgmt_db}}.GOVERNANCE_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA {{mgmt_db}}.ACCESS_GOVERNANCE TO DATABASE ROLE {{mgmt_db}}.GOVERNANCE_READER;


GRANT CREATE TABLE, CREATE VIEW ON SCHEMA {{mgmt_db}}.COST_GOVERNANCE TO DATABASE ROLE {{mgmt_db}}.GOVERNANCE_ADMIN;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {{mgmt_db}}.COST_GOVERNANCE TO DATABASE ROLE {{mgmt_db}}.GOVERNANCE_ADMIN;

GRANT CREATE TABLE, CREATE VIEW ON SCHEMA {{mgmt_db}}.ACCESS_GOVERNANCE TO DATABASE ROLE {{mgmt_db}}.GOVERNANCE_ADMIN;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {{mgmt_db}}.ACCESS_GOVERNANCE TO DATABASE ROLE {{mgmt_db}}.GOVERNANCE_ADMIN;

GRANT USAGE ON SCHEMA {{mgmt_db}}.CONFIG TO DATABASE ROLE {{mgmt_db}}.GOVERNANCE_ADMIN;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA {{mgmt_db}}.CONFIG TO DATABASE ROLE {{mgmt_db}}.GOVERNANCE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {{mgmt_db}}.CONFIG TO DATABASE ROLE {{mgmt_db}}.GOVERNANCE_ADMIN;

GRANT USAGE ON SCHEMA {{mgmt_db}}.ORCHESTRATION TO DATABASE ROLE {{mgmt_db}}.GOVERNANCE_ADMIN;
GRANT CREATE TABLE, CREATE VIEW, CREATE TASK ON SCHEMA {{mgmt_db}}.ORCHESTRATION TO DATABASE ROLE {{mgmt_db}}.GOVERNANCE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {{mgmt_db}}.ORCHESTRATION TO DATABASE ROLE {{mgmt_db}}.GOVERNANCE_ADMIN;


-- INGESTION ROLE (data engineering — stages, pipes, loading into RAW)

DEFINE ROLE INGESTION_ROLE{{env_suffix}}
    COMMENT = 'Service role for data ingestion — creates stages, pipes and loads into RAW schemas';

GRANT ROLE INGESTION_ROLE{{env_suffix}} TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH{{env_suffix}} TO ROLE INGESTION_ROLE{{env_suffix}};

{% for db_var in [fin_db, mkt_db, eco_db, ret_db, loy_db] %}
GRANT USAGE ON DATABASE {{db_var}} TO ROLE INGESTION_ROLE{{env_suffix}};
GRANT USAGE ON SCHEMA {{db_var}}.RAW TO ROLE INGESTION_ROLE{{env_suffix}};
GRANT CREATE TABLE, CREATE STAGE, CREATE PIPE, CREATE FILE FORMAT ON SCHEMA {{db_var}}.RAW TO ROLE INGESTION_ROLE{{env_suffix}};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {{db_var}}.RAW TO ROLE INGESTION_ROLE{{env_suffix}};
{% endfor %}


-- TRANSFORM ROLE (dbt / ELT service account)

DEFINE ROLE TRANSFORM_ROLE{{env_suffix}}
    COMMENT = 'Service role for dbt/ELT — reads RAW, writes STAGING + MARTS across all domains';

GRANT ROLE TRANSFORM_ROLE{{env_suffix}} TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH{{env_suffix}} TO ROLE TRANSFORM_ROLE{{env_suffix}};

{% for db_var in [fin_db, mkt_db, eco_db, ret_db, loy_db] %}
GRANT USAGE ON DATABASE {{db_var}} TO ROLE TRANSFORM_ROLE{{env_suffix}};
GRANT USAGE ON SCHEMA {{db_var}}.RAW TO ROLE TRANSFORM_ROLE{{env_suffix}};
GRANT SELECT ON ALL TABLES IN SCHEMA {{db_var}}.RAW TO ROLE TRANSFORM_ROLE{{env_suffix}};

GRANT USAGE ON SCHEMA {{db_var}}.STAGING TO ROLE TRANSFORM_ROLE{{env_suffix}};
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA {{db_var}}.STAGING TO ROLE TRANSFORM_ROLE{{env_suffix}};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {{db_var}}.STAGING TO ROLE TRANSFORM_ROLE{{env_suffix}};

GRANT USAGE ON SCHEMA {{db_var}}.MARTS TO ROLE TRANSFORM_ROLE{{env_suffix}};
GRANT CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE ON SCHEMA {{db_var}}.MARTS TO ROLE TRANSFORM_ROLE{{env_suffix}};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {{db_var}}.MARTS TO ROLE TRANSFORM_ROLE{{env_suffix}};
{% endfor %}

GRANT USAGE ON DATABASE {{ana_db}} TO ROLE TRANSFORM_ROLE{{env_suffix}};
GRANT USAGE ON SCHEMA {{ana_db}}.MARTS TO ROLE TRANSFORM_ROLE{{env_suffix}};
GRANT CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE ON SCHEMA {{ana_db}}.MARTS TO ROLE TRANSFORM_ROLE{{env_suffix}};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {{ana_db}}.MARTS TO ROLE TRANSFORM_ROLE{{env_suffix}};

GRANT USAGE ON DATABASE {{mgmt_db}} TO ROLE TRANSFORM_ROLE{{env_suffix}};
GRANT USAGE ON SCHEMA {{mgmt_db}}.COST_GOVERNANCE TO ROLE TRANSFORM_ROLE{{env_suffix}};
GRANT CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE ON SCHEMA {{mgmt_db}}.COST_GOVERNANCE TO ROLE TRANSFORM_ROLE{{env_suffix}};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {{mgmt_db}}.COST_GOVERNANCE TO ROLE TRANSFORM_ROLE{{env_suffix}};
GRANT USAGE ON SCHEMA {{mgmt_db}}.ACCESS_GOVERNANCE TO ROLE TRANSFORM_ROLE{{env_suffix}};
GRANT CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE ON SCHEMA {{mgmt_db}}.ACCESS_GOVERNANCE TO ROLE TRANSFORM_ROLE{{env_suffix}};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {{mgmt_db}}.ACCESS_GOVERNANCE TO ROLE TRANSFORM_ROLE{{env_suffix}};


-- CROSS-DOMAIN READ ACCESS

{% for db_var in [fin_db, mkt_db, eco_db, ret_db, loy_db] %}
GRANT DATABASE ROLE {{db_var}}.READER TO DATABASE ROLE {{ana_db}}.ADMIN;
{% endfor %}